epoch: 3000
patience: 1000
accelerator: cpu
devices: 1

model: RNNPolicy
datamodule: LissajousDataModule

dataset_config:
    data_num: 100
    points_num: 50
    round_times: 2
    noise_std: 0.1
    batch_size: 20

model_config:
    input_size: 2
    hidden_size: 16
    output_size: 2
    num_hidden_layers: 1
    activation: ReLU
    out_activation: Identity
    num_mix: 2
    optimizer: Adam
    lr: 1.0e-3
