epoch: 10000
patience: 1000
accelerator: gpu
devices:
    - 0

model: TransformerPolicy
datamodule: RobotDataModule

dataset_config:
    batch_size: 256
    data_name: fuji_put_ball_lv4
    window_size: 20
    window_stride: 10

model_config:
    input_size: 14
    # GPT
    gpt_num_heads: 4
    gpt_ff_dim: 64
    gpt_num_layers: 4
    gpt_embed_dim: 128
    gpt_activation: ReLU
    gpt_dropout: 0.1
    max_seq_len: 512
    # MLP
    output_size: 14
    num_hidden_layers: 1
    hidden_size: 128
    activation: ReLU
    out_activation: Identity
    num_mix: 2
    optimizer: Adam
    lr: 1.0e-3

test:
    open:
        batch_indices:
            - 10
            - 20
            - 30
    closed:
        generation_length: 150
        batch_indices:
            - 10
